# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created: Wed Jul 22 23:57:08 2015
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(517, 310)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(251, 252, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(251, 252, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(251, 252, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(251, 252, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(251, 252, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(251, 252, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(251, 252, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(251, 252, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(251, 252, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("oselya.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(_fromUtf8("background-color: rgb(251, 252, 255);"))
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(7, 7, 7, -1)
        self.gridLayout_2.setHorizontalSpacing(5)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setStyleSheet(_fromUtf8("color: rgb(0, 0, 97);"))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet(_fromUtf8("gridline-color: rgb(0, 0, 143);"))
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.date_start = QtGui.QDateEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_start.sizePolicy().hasHeightForWidth())
        self.date_start.setSizePolicy(sizePolicy)
        self.date_start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.date_start.setStyleSheet(_fromUtf8("gridline-color: rgb(0, 0, 143);"))
        self.date_start.setDate(QtCore.QDate(2014, 8, 10))
        self.date_start.setCalendarPopup(True)
        self.date_start.setObjectName(_fromUtf8("date_start"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.date_start)
        self.label_2 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet(_fromUtf8("gridline-color: rgb(0, 0, 143);"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.date_end = QtGui.QDateEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_end.sizePolicy().hasHeightForWidth())
        self.date_end.setSizePolicy(sizePolicy)
        self.date_end.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.date_end.setStyleSheet(_fromUtf8("gridline-color: rgb(0, 0, 143);"))
        self.date_end.setDate(QtCore.QDate(2016, 3, 31))
        self.date_end.setCalendarPopup(True)
        self.date_end.setObjectName(_fromUtf8("date_end"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.date_end)
        self.label_3 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setItalic(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(_fromUtf8("gridline-color: rgb(0, 0, 143);"))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.SpinBox_square = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SpinBox_square.sizePolicy().hasHeightForWidth())
        self.SpinBox_square.setSizePolicy(sizePolicy)
        self.SpinBox_square.setMaximumSize(QtCore.QSize(87, 16777215))
        self.SpinBox_square.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SpinBox_square.setStyleSheet(_fromUtf8("gridline-color: rgb(0, 0, 143);"))
        self.SpinBox_square.setAccelerated(True)
        self.SpinBox_square.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToNearestValue)
        self.SpinBox_square.setKeyboardTracking(False)
        self.SpinBox_square.setPrefix(_fromUtf8(""))
        self.SpinBox_square.setMaximum(300.99)
        self.SpinBox_square.setProperty("value", 67.46)
        self.SpinBox_square.setObjectName(_fromUtf8("SpinBox_square"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.SpinBox_square)
        self.label_4 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setStyleSheet(_fromUtf8("gridline-color: rgb(0, 0, 143);"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.spinBox_price = QtGui.QSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_price.sizePolicy().hasHeightForWidth())
        self.spinBox_price.setSizePolicy(sizePolicy)
        self.spinBox_price.setMaximumSize(QtCore.QSize(87, 16777215))
        self.spinBox_price.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spinBox_price.setStyleSheet(_fromUtf8("gridline-color: rgb(0, 0, 143);"))
        self.spinBox_price.setAccelerated(True)
        self.spinBox_price.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToNearestValue)
        self.spinBox_price.setKeyboardTracking(False)
        self.spinBox_price.setMinimum(5000)
        self.spinBox_price.setMaximum(20000)
        self.spinBox_price.setSingleStep(100)
        self.spinBox_price.setProperty("value", 6200)
        self.spinBox_price.setObjectName(_fromUtf8("spinBox_price"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.spinBox_price)
        self.label_5 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setStyleSheet(_fromUtf8("gridline-color: rgb(0, 0, 143);"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.spinBox_prepainment = QtGui.QSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_prepainment.sizePolicy().hasHeightForWidth())
        self.spinBox_prepainment.setSizePolicy(sizePolicy)
        self.spinBox_prepainment.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spinBox_prepainment.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.spinBox_prepainment.setStyleSheet(_fromUtf8("gridline-color: rgb(0, 0, 143);"))
        self.spinBox_prepainment.setAccelerated(True)
        self.spinBox_prepainment.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToNearestValue)
        self.spinBox_prepainment.setKeyboardTracking(False)
        self.spinBox_prepainment.setPrefix(_fromUtf8(""))
        self.spinBox_prepainment.setMinimum(0)
        self.spinBox_prepainment.setMaximum(1000000)
        self.spinBox_prepainment.setSingleStep(100)
        self.spinBox_prepainment.setProperty("value", 125500)
        self.spinBox_prepainment.setObjectName(_fromUtf8("spinBox_prepainment"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.spinBox_prepainment)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setStyleSheet(_fromUtf8("color: rgb(0, 0, 97);"))
        self.groupBox_2.setTitle(_fromUtf8("Calculation"))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setContentsMargins(-1, -1, 5, -1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.spinBox_total = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_total.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_total.sizePolicy().hasHeightForWidth())
        self.spinBox_total.setSizePolicy(sizePolicy)
        self.spinBox_total.setMinimumSize(QtCore.QSize(84, 0))
        self.spinBox_total.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spinBox_total.setWrapping(False)
        self.spinBox_total.setFrame(True)
        self.spinBox_total.setReadOnly(True)
        self.spinBox_total.setAccelerated(False)
        self.spinBox_total.setPrefix(_fromUtf8(""))
        self.spinBox_total.setMinimum(200000)
        self.spinBox_total.setMaximum(2000000)
        self.spinBox_total.setSingleStep(10)
        self.spinBox_total.setProperty("value", 200000)
        self.spinBox_total.setObjectName(_fromUtf8("spinBox_total"))
        self.gridLayout.addWidget(self.spinBox_total, 1, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 2)
        self.spinBox_mon_pay = QtGui.QSpinBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_mon_pay.sizePolicy().hasHeightForWidth())
        self.spinBox_mon_pay.setSizePolicy(sizePolicy)
        self.spinBox_mon_pay.setMinimumSize(QtCore.QSize(84, 0))
        self.spinBox_mon_pay.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spinBox_mon_pay.setWrapping(False)
        self.spinBox_mon_pay.setFrame(True)
        self.spinBox_mon_pay.setSpecialValueText(_fromUtf8(""))
        self.spinBox_mon_pay.setAccelerated(True)
        self.spinBox_mon_pay.setCorrectionMode(QtGui.QAbstractSpinBox.CorrectToNearestValue)
        self.spinBox_mon_pay.setKeyboardTracking(False)
        self.spinBox_mon_pay.setPrefix(_fromUtf8(""))
        self.spinBox_mon_pay.setMinimum(1000)
        self.spinBox_mon_pay.setMaximum(2000000)
        self.spinBox_mon_pay.setSingleStep(100)
        self.spinBox_mon_pay.setProperty("value", 15410)
        self.spinBox_mon_pay.setObjectName(_fromUtf8("spinBox_mon_pay"))
        self.gridLayout.addWidget(self.spinBox_mon_pay, 2, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 3, 0, 1, 2)
        self.spinBox_balance_amount = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_balance_amount.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_balance_amount.sizePolicy().hasHeightForWidth())
        self.spinBox_balance_amount.setSizePolicy(sizePolicy)
        self.spinBox_balance_amount.setMinimumSize(QtCore.QSize(84, 0))
        self.spinBox_balance_amount.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spinBox_balance_amount.setWrapping(True)
        self.spinBox_balance_amount.setFrame(True)
        self.spinBox_balance_amount.setReadOnly(True)
        self.spinBox_balance_amount.setAccelerated(False)
        self.spinBox_balance_amount.setPrefix(_fromUtf8(""))
        self.spinBox_balance_amount.setMinimum(200000)
        self.spinBox_balance_amount.setMaximum(2000000)
        self.spinBox_balance_amount.setSingleStep(10)
        self.spinBox_balance_amount.setProperty("value", 200000)
        self.spinBox_balance_amount.setObjectName(_fromUtf8("spinBox_balance_amount"))
        self.gridLayout.addWidget(self.spinBox_balance_amount, 3, 2, 1, 1)
        self.line_3 = QtGui.QFrame(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setMinimumSize(QtCore.QSize(0, 2))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 4, 0, 1, 3)
        self.label_12 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 6, 0, 1, 3, QtCore.Qt.AlignLeft)
        self.date_inflation = QtGui.QDateEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date_inflation.sizePolicy().hasHeightForWidth())
        self.date_inflation.setSizePolicy(sizePolicy)
        self.date_inflation.setMinimumSize(QtCore.QSize(68, 0))
        self.date_inflation.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.date_inflation.setDate(QtCore.QDate(2014, 8, 10))
        self.date_inflation.setCalendarPopup(True)
        self.date_inflation.setObjectName(_fromUtf8("date_inflation"))
        self.gridLayout.addWidget(self.date_inflation, 7, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.spinBox_mon_percent = QtGui.QSpinBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_mon_percent.sizePolicy().hasHeightForWidth())
        self.spinBox_mon_percent.setSizePolicy(sizePolicy)
        self.spinBox_mon_percent.setMinimumSize(QtCore.QSize(40, 0))
        self.spinBox_mon_percent.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spinBox_mon_percent.setWrapping(True)
        self.spinBox_mon_percent.setFrame(True)
        self.spinBox_mon_percent.setAccelerated(False)
        self.spinBox_mon_percent.setPrefix(_fromUtf8(""))
        self.spinBox_mon_percent.setMinimum(0)
        self.spinBox_mon_percent.setMaximum(200)
        self.spinBox_mon_percent.setSingleStep(1)
        self.spinBox_mon_percent.setProperty("value", 10)
        self.spinBox_mon_percent.setObjectName(_fromUtf8("spinBox_mon_percent"))
        self.gridLayout.addWidget(self.spinBox_mon_percent, 7, 1, 1, 1)
        self.spinBox_mon_uah = QtGui.QSpinBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_mon_uah.sizePolicy().hasHeightForWidth())
        self.spinBox_mon_uah.setSizePolicy(sizePolicy)
        self.spinBox_mon_uah.setMinimumSize(QtCore.QSize(84, 0))
        self.spinBox_mon_uah.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spinBox_mon_uah.setWrapping(True)
        self.spinBox_mon_uah.setFrame(True)
        self.spinBox_mon_uah.setAccelerated(False)
        self.spinBox_mon_uah.setPrefix(_fromUtf8(""))
        self.spinBox_mon_uah.setMinimum(0)
        self.spinBox_mon_uah.setMaximum(50000)
        self.spinBox_mon_uah.setSingleStep(10)
        self.spinBox_mon_uah.setProperty("value", 0)
        self.spinBox_mon_uah.setObjectName(_fromUtf8("spinBox_mon_uah"))
        self.gridLayout.addWidget(self.spinBox_mon_uah, 7, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 8, 1, 1, 2)
        self.spinBox_total_percent = QtGui.QSpinBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_total_percent.sizePolicy().hasHeightForWidth())
        self.spinBox_total_percent.setSizePolicy(sizePolicy)
        self.spinBox_total_percent.setMinimumSize(QtCore.QSize(40, 0))
        self.spinBox_total_percent.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spinBox_total_percent.setWrapping(True)
        self.spinBox_total_percent.setFrame(True)
        self.spinBox_total_percent.setAccelerated(False)
        self.spinBox_total_percent.setPrefix(_fromUtf8(""))
        self.spinBox_total_percent.setMinimum(0)
        self.spinBox_total_percent.setMaximum(200)
        self.spinBox_total_percent.setSingleStep(1)
        self.spinBox_total_percent.setProperty("value", 0)
        self.spinBox_total_percent.setObjectName(_fromUtf8("spinBox_total_percent"))
        self.gridLayout.addWidget(self.spinBox_total_percent, 9, 1, 1, 1)
        self.spinBoxtotal_uah = QtGui.QSpinBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxtotal_uah.sizePolicy().hasHeightForWidth())
        self.spinBoxtotal_uah.setSizePolicy(sizePolicy)
        self.spinBoxtotal_uah.setMinimumSize(QtCore.QSize(84, 0))
        self.spinBoxtotal_uah.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spinBoxtotal_uah.setWrapping(True)
        self.spinBoxtotal_uah.setFrame(True)
        self.spinBoxtotal_uah.setAccelerated(False)
        self.spinBoxtotal_uah.setPrefix(_fromUtf8(""))
        self.spinBoxtotal_uah.setMinimum(0)
        self.spinBoxtotal_uah.setMaximum(500000)
        self.spinBoxtotal_uah.setSingleStep(10)
        self.spinBoxtotal_uah.setProperty("value", 0)
        self.spinBoxtotal_uah.setObjectName(_fromUtf8("spinBoxtotal_uah"))
        self.gridLayout.addWidget(self.spinBoxtotal_uah, 9, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox.sizePolicy().hasHeightForWidth())
        self.checkBox.setSizePolicy(sizePolicy)
        self.checkBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout.addWidget(self.checkBox, 5, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 1, 1, 1, QtCore.Qt.AlignLeft)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionClear_all = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../Python27/to_exe/py2exe/img/green.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClear_all.setIcon(icon1)
        self.actionClear_all.setObjectName(_fromUtf8("actionClear_all"))
        self.actionSave_as_txt = QtGui.QAction(MainWindow)
        self.actionSave_as_txt.setIcon(icon1)
        self.actionSave_as_txt.setObjectName(_fromUtf8("actionSave_as_txt"))
        self.actionExit = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../Python27/to_exe/py2exe/img/red.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon2)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.date_start, QtCore.SIGNAL(_fromUtf8("dateChanged(QDate)")), self.spinBox_mon_pay.clear)
        QtCore.QObject.connect(self.date_end, QtCore.SIGNAL(_fromUtf8("dateChanged(QDate)")), self.spinBox_mon_pay.clear)
        QtCore.QObject.connect(self.SpinBox_square, QtCore.SIGNAL(_fromUtf8("valueChanged(QString)")), self.spinBox_total.clear)
        QtCore.QObject.connect(self.spinBox_price, QtCore.SIGNAL(_fromUtf8("valueChanged(QString)")), self.spinBox_total.clear)
        QtCore.QObject.connect(self.spinBox_prepainment, QtCore.SIGNAL(_fromUtf8("valueChanged(QString)")), self.spinBox_balance_amount.clear)
        QtCore.QObject.connect(self.spinBox_total, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_balance_amount.clear)
        QtCore.QObject.connect(self.checkBox, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), self.spinBox_mon_percent.clear)
        QtCore.QObject.connect(self.checkBox, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), self.spinBox_mon_uah.clear)
        QtCore.QObject.connect(self.checkBox, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), self.spinBox_total_percent.clear)
        QtCore.QObject.connect(self.checkBox, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), self.spinBoxtotal_uah.clear)
        QtCore.QObject.connect(self.spinBox_mon_pay, QtCore.SIGNAL(_fromUtf8("valueChanged(QString)")), self.spinBox_mon_uah.clear)
        QtCore.QObject.connect(self.date_inflation, QtCore.SIGNAL(_fromUtf8("dateChanged(QDate)")), self.spinBox_mon_percent.clear)
        QtCore.QObject.connect(self.date_inflation, QtCore.SIGNAL(_fromUtf8("dateChanged(QDate)")), self.spinBox_mon_uah.clear)
        QtCore.QObject.connect(self.date_start, QtCore.SIGNAL(_fromUtf8("dateChanged(QDate)")), self.spinBox_total_percent.clear)
        QtCore.QObject.connect(self.date_end, QtCore.SIGNAL(_fromUtf8("dateChanged(QDate)")), self.spinBoxtotal_uah.clear)
        QtCore.QObject.connect(self.date_start, QtCore.SIGNAL(_fromUtf8("dateChanged(QDate)")), self.spinBoxtotal_uah.clear)
        QtCore.QObject.connect(self.spinBox_prepainment, QtCore.SIGNAL(_fromUtf8("valueChanged(QString)")), self.spinBox_mon_pay.clear)
        QtCore.QObject.connect(self.spinBox_total, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBox_mon_pay.clear)
        QtCore.QObject.connect(self.date_end, QtCore.SIGNAL(_fromUtf8("dateChanged(QDate)")), self.spinBox_total_percent.clear)
        QtCore.QObject.connect(self.date_end, QtCore.SIGNAL(_fromUtf8("dateChanged(QDate)")), self.spinBoxtotal_uah.clear)
        QtCore.QObject.connect(self.SpinBox_square, QtCore.SIGNAL(_fromUtf8("valueChanged(QString)")), self.spinBox_mon_pay.clear)
        QtCore.QObject.connect(self.spinBox_price, QtCore.SIGNAL(_fromUtf8("valueChanged(QString)")), self.spinBox_mon_pay.clear)
        QtCore.QObject.connect(self.spinBox_prepainment, QtCore.SIGNAL(_fromUtf8("valueChanged(QString)")), self.spinBox_mon_pay.clear)
        QtCore.QObject.connect(self.SpinBox_square, QtCore.SIGNAL(_fromUtf8("valueChanged(QString)")), self.spinBox_balance_amount.clear)
        QtCore.QObject.connect(self.spinBox_price, QtCore.SIGNAL(_fromUtf8("valueChanged(QString)")), self.spinBox_balance_amount.clear)
        QtCore.QObject.connect(self.spinBox_prepainment, QtCore.SIGNAL(_fromUtf8("valueChanged(QString)")), self.spinBox_balance_amount.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.date_start, self.date_end)
        MainWindow.setTabOrder(self.date_end, self.SpinBox_square)
        MainWindow.setTabOrder(self.SpinBox_square, self.spinBox_price)
        MainWindow.setTabOrder(self.spinBox_price, self.spinBox_prepainment)
        MainWindow.setTabOrder(self.spinBox_prepainment, self.spinBox_total)
        MainWindow.setTabOrder(self.spinBox_total, self.spinBox_mon_pay)
        MainWindow.setTabOrder(self.spinBox_mon_pay, self.spinBox_balance_amount)
        MainWindow.setTabOrder(self.spinBox_balance_amount, self.date_inflation)
        MainWindow.setTabOrder(self.date_inflation, self.spinBox_mon_percent)
        MainWindow.setTabOrder(self.spinBox_mon_percent, self.spinBox_mon_uah)
        MainWindow.setTabOrder(self.spinBox_mon_uah, self.spinBox_total_percent)
        MainWindow.setTabOrder(self.spinBox_total_percent, self.spinBoxtotal_uah)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Payment", None))
        self.groupBox.setTitle(_translate("MainWindow", "Contract data", None))
        self.label.setText(_translate("MainWindow", "Purchase date", None))
        self.date_start.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy", None))
        self.label_2.setText(_translate("MainWindow", "Completion date", None))
        self.date_end.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy", None))
        self.label_3.setText(_translate("MainWindow", "Apartment area", None))
        self.SpinBox_square.setSuffix(_translate("MainWindow", " m2", None))
        self.label_4.setText(_translate("MainWindow", "Price for one meter", None))
        self.spinBox_price.setSuffix(_translate("MainWindow", " UAH", None))
        self.label_5.setText(_translate("MainWindow", "Prepayment", None))
        self.spinBox_prepainment.setSuffix(_translate("MainWindow", " UAH", None))
        self.spinBox_total.setSuffix(_translate("MainWindow", " UAH", None))
        self.label_8.setText(_translate("MainWindow", "Monthly payment", None))
        self.spinBox_mon_pay.setSuffix(_translate("MainWindow", " UAH", None))
        self.label_9.setText(_translate("MainWindow", "Balance amount", None))
        self.spinBox_balance_amount.setSuffix(_translate("MainWindow", " UAH", None))
        self.label_12.setText(_translate("MainWindow", "Additional monthly payment (current month by default)", None))
        self.date_inflation.setDisplayFormat(_translate("MainWindow", "MM.yyyy", None))
        self.spinBox_mon_percent.setSuffix(_translate("MainWindow", "%", None))
        self.spinBox_mon_uah.setSuffix(_translate("MainWindow", " UAH", None))
        self.label_11.setText(_translate("MainWindow", "Total payment of inflation", None))
        self.spinBox_total_percent.setSuffix(_translate("MainWindow", "%", None))
        self.spinBoxtotal_uah.setSuffix(_translate("MainWindow", " UAH", None))
        self.label_6.setText(_translate("MainWindow", "Total ", None))
        self.checkBox.setText(_translate("MainWindow", "Include inflation index", None))
        self.actionClear_all.setText(_translate("MainWindow", "Clear all", None))
        self.actionSave_as_txt.setText(_translate("MainWindow", "Save as .txt", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))

